{
	"version": 1684686494,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/background.png",
		"images/player-sheet0.png",
		"images/monster-sheet0.png",
		"images/bullet-sheet0.png",
		"images/explosion-sheet0.png",
		"images/blood-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/tiledbackground2.png",
		"images/shotgun-sheet0.png",
		"images/monster3-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground3.png",
		"media/drobovik-27711.ogg",
		"media/horoshiy-blizkiy-odinochnyiy-vyistrel.ogg",
		"media/vyistrelyi-iz-avtomata-po-dalney-tseli.ogg",
		"media/vyistrel-iz-pistoleta2.ogg",
		"media/tresk-slomannogo-predmeta.ogg",
		"media/ston.ogg",
		"media/ston-2.ogg",
		"media/phone.m4a",
		"media/du.m4a",
		"media/rammstein - du hast.ogg",
		"media/099 - creedence clearwater revival - fortunate son _1969_.m4a",
		"media/099 - creedence clearwater revival - fortunate son _1969_.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}